buff_predictor_node:
  ros__parameters:
    target_frame: odom
    camera_frame: camera_optical_frame
    debug_mode: true
    debug_csv_path: buff_predictor_debug.csv
    physical_arm_length: 1.5
    velocity_median_window: 3
    camera_fx: 1303.675283386667
    camera_fy: 1303.675283386667
    camera_cx: 720.0
    camera_cy: 540.0
    fit_window_sec: 1.5
    fit_min_samples: 10
    fit_offset_sum: 2.090
    fit_a_lower: 0.780
    fit_a_upper: 1.045
    fit_omega_lower: 1.884
    fit_omega_upper: 2.000
    fit_phi_lower: -3.141592653589793
    fit_phi_upper: 3.141592653589793
