buff_detector_node:
  ros__parameters:
    model_path: src/buff_detector/model/Fan.onnx
    confidence_threshold: 0.5
    iou_threshold: 0.5
    debug_mode: true
    inside_shade_rate: 0.7
    outside_shade_rate: 1.39
    lower_h: 0
    lower_s: 40
    lower_v: 220
    upper_h: 70
    upper_s: 255
    upper_v: 255
    dilate_kernel_size: 7
    max_lost_frame: 5
    debug_image_frame_id: camera
