# ======================================================================
# 能量机关自瞄系统参数配置文件
# 用于 buff_detector、buff_estimator、buff_aimer、buff_debug_visualizer
# ======================================================================

# -------------------- 检测节点 (buff_detector) --------------------
buff_detector_node:
  ros__parameters:
      model_path: model/yolo11_buff_int8.xml
      openvino_device: GPU
      confidence_threshold: 0.70
      debug_mode: true
      image_reliable: true
      buff_mode: auto




# -------------------- 状态估计节点 (buff_estimator) --------------------
buff_estimator_node:
  ros__parameters:
    target_frame: odom
    camera_frame: camera_optical_frame
    debug_mode: true
    debug_csv_path: buff_estimator_debug.csv
    max_reprojection_error_px: 12.0
    geometry_buffer_sec: 5.0
    geometry_min_samples: 20
    geometry_min_span_sec: 1.0
    max_model_residual_m: 0.25
    max_plane_rms_m: 0.08
    max_circle_rms_m: 0.10
    velocity_median_window: 3
    velocity_sample_window_sec: 4.0
    max_velocity_sample_abs: 8.0
    fit_window_sec: 1.5
    fit_min_samples: 10
    fit_offset_sum: 2.090
    
    fit_a_range: [0.780, 1.045]
    fit_omega_range: [1.884, 2.000]
    fit_phi_range: [-3.141592653589793, 3.141592653589793]




# -------------------- 自瞄输出节点 (buff_aimer) --------------------
buff_aimer_node:
  ros__parameters:
    ballistic:
      bullet_speed: 23.8
      shoot_delay: 0.05
      gravity: 9.81
      air_k: 0.019
      converge_thresh: 0.002
      sim_dt: 0.005
    aiming:
      debug: true
    frames:
      target: "odom"




# -------------------- 世界模型调试图像节点 (buff_debug_visualizer) --------------------
buff_debug_visualizer_node:
  ros__parameters:
    enabled: true
    topics:
      image: /image_raw
      camera_info: /camera_info
      aiming_data: /buff/aiming_data
      output_image: /buff/world_model_debug_image
    frames:
      camera: camera_optical_frame
    circle_samples: 144
    normal_length_scale: 0.8
    stale_timeout_sec: 0.25
