/armor_detector_node:
  ros__parameters:
    debug: true

    detect_color: 0
    binary_thres: 50

    light.min_ratio: 0.1
    light.max_ratio: 0.4
    light.max_angle: 35.0
    light.min_fill_ratio: 0.6
    armor.min_light_ratio: 0.8

    classifier_threshold: 0.6
    ignore_classes: ["negative"]


/armor_tracker_node:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 15.0

    ekf:
      #igma2_q_xyz_max: 0.5
      #sigma2_q_xyz_min: 0.1
      #sigma2_q_yaw_max: 100.0
      #sigma2_q_yaw_min: 30.0
      #sigma2_q_r: 40.0

      #r_xyz_factor: 6e-3
      #r_yaw: 0.1
      #r_radius: 1e100
      
      sigma2_q_xyz_max: 10.0
      sigma2_q_xyz_min: 1.0
      #sigma2_q_yaw_max: 15.0
      #sigma2_q_yaw_min: 5.0
      sigma2_q_yaw_max: 5.0
      sigma2_q_yaw_min: 1.0
      sigma2_q_r: 40.0

      r_xyz_factor: 4.0e-2
      r_yaw: 1.0e-2

    tracker:
      max_match_distance: 1.5
      max_match_yaw_diff: 0.8

      tracking_thres: 5
      lost_time_thres: 1.0



/rm_auto_record:
  ros__parameters:
    uri: "/ros_ws/"
    topic_name:
    - "/image_raw/compressed"
    - "/camera_info"
    - "/detector/armors"
    topic_type:
    - "sensor_msgs/msg/CompressedImage"
    - "sensor_msgs/msg/CameraInfo"
    - "auto_aim_interfaces/msg/Armors"
